version: '3'
services:
  web:
    build: .
    container_name: web
    command: bundle exec rails s
    environment:
      RAILS_ENV: development
    depends_on:
      - mysql
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/rspec_app
      - node-modules:/rspec_app/node_modules
      - bundle:/usr/local/bundle
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/mysql
volumes:
  node-modules:
  bundle: